In [1]:
import numpy as np

In [4]:
A = np.array([[1,2,3], [2,7,4]])
B = np.array([[1,-1], [0,1]])
C = np.array([[5,-1], [9,1], [6,0]])
D = np.array([[3,-2,-1], [1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

In [5]:
dimensions = {
    'A': A.shape,
    'B': B.shape,
    'C': C.shape,
    'D': D.shape,
    'u': u.shape,
    'v': v.shape
}

In [6]:
dimensions

{'A': (2, 3), 'B': (2, 2), 'C': (3, 2), 'D': (2, 3), 'u': (4,), 'v': (4,)}

In [8]:
alpha = 6

u_plus_v = np.add(u,v)
u_minus_v = np.subtract(u,v)
alpha_times_u = alpha * u
u_dot_v = u.dot(v)
norm_u = np.sqrt(u.dot(u))

In [11]:
print(u_plus_v)
print(u_minus_v)
print(alpha_times_u)
print(u_dot_v)
print(norm_u)

[ 9  7 -4  9]
[ 3 -3 -2  1]
[ 36  12 -18  30]
51
8.602325267042627


In [14]:
A_plus_C = None # dimensions of A and C do not match
A_minus_Ctranspose = np.subtract(A, C.T)
Ctranspose_plus_3D = np.add(C.T, 3*D)
B_times_A = B.dot(A)
B_times_Atranspose = None # dimensions do not match for matrix mult

In [15]:
print(A_plus_C)
print(A_minus_Ctranspose)
print(Ctranspose_plus_3D)
print(B_times_A)
print(B_times_Atranspose)

None
[[-4 -7 -3]
 [ 3  6  4]]
[[14  3  3]
 [ 2  7  9]]
[[-1 -5 -1]
 [ 2  7  4]]
None


In [16]:
B_times_C = None # dimensions do not match for matrix mult
C_times_B = C.dot(B)
B_exp_4 = np.dot(B.dot(B), B.dot(B))
A_times_Atranspose = A.dot(A.T)
Dtranspose_times_D = D.T.dot(D)

In [17]:
print(B_times_C)
print(C_times_B)
print(B_exp_4)
print(A_times_Atranspose)
print(Dtranspose_times_D)

None
[[ 5 -6]
 [ 9 -8]
 [ 6 -6]]
[[ 1 -4]
 [ 0  1]]
[[14 28]
 [28 69]]
[[10 -4  0]
 [-4  8  8]
 [ 0  8 10]]
